name = "katelyatv"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 生产环境配置
[env.production]
name = "katelyatv"

# 生产环境 D1 数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "0bbb6567-68eb-4005-96cd-618965b260e9"

# 生产环境变量
[env.production.vars]
NEXT_PUBLIC_STORAGE_TYPE = "d1"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
NEXT_PUBLIC_SITE_NAME = "KatelyaTV"
NEXT_PUBLIC_SITE_DESCRIPTION = "mytv"
NEXTAUTH_URL = "https://kmytv.pages.dev/"  # 替换为您的 Pages 域名
IMAGE_PROXY_ENABLED = "true"
CACHE_TTL = "3600"
CORS_ORIGIN = "https://kmytv.pages.dev/"  # 替换为实际域名，限制跨域
RATE_LIMIT_MAX = "100"
RATE_LIMIT_WINDOW = "60000"
HEALTH_CHECK_ENABLED = "true"
HEALTH_CHECK_INTERVAL = "30"
LOG_LEVEL = "info"
LOG_FORMAT = "json"
NODE_ENV = "production"
